
const FACEBOOK_ACCESS_KEY = {
    TWITTER_CONSUMER_KEY: "SOME KEY",
    TWITTER_CONSUMER_SECRET: "SOME SECRET",
    TWITTER_ACCESS_TOKEN: "SOME ACCESS TOKEN",
    TWITTER_TOKEN_SECRET: "SOME TOKEN SECRET"
};
const SESSION = {
    COOKIE_KEY: "thisappisawesome"
};
const KEYS = {
    ...FACEBOOK_ACCESS_KEY,
    ...SESSION,
};

module.exports = KEYS;